apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.configMapName }}
  labels:
    app: {{ .Values.feapp.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS {{ .Values.mysql.databaseName }};
    CREATE DATABASE {{ .Values.mysql.databaseName }};
    USE {{ .Values.mysql.databaseName }};

    CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL
    );