apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.feapp.name }}
spec:
  type: {{ .Values.feapp.service.type | default "ClusterIP" }}
  selector:
    app: fe-app
  ports:
    - protocol: TCP
      port: {{ .Values.feapp.service.port | default 80 }}
      targetPort: {{ .Values.feapp.service.targetPort | default 3000 }}